services:
  postgres:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION:?error}
        PGDATA: ${PGDATA:?error}
        POSTGRES_PORT: ${POSTGRES_PORT:?error}
        CLUSTER_NAME: ${CLUSTER_NAME:?error}
    container_name: postgres-container
    restart: on-failure:5
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:${PGDATA:-/var/lib/postgresql/data}
    healthcheck:
      # Docker Compose will use this for service health checks
      test: [ "CMD-SHELL", "/usr/local/bin/healthcheck.sh" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 20s # Give PostgreSQL time to initialize
      disable: false

volumes:
  postgres_data:
